Fix lint error
The current code in BMO fails to build because of a missing import

Error: hostfirmwarecomponents_controller.go:132:6: undefined: errors (typecheck)

This commit fixes this issue.

Signed-off-by: Iury Gregory Melo Ferreira <imelofer@redhat.com>